"""Patch seed_data.py — replace abbreviated dialogue arrays with full content from NPCR 1-14.docx."""
import re

NEW_DIALOGUES = {
    3: [
        {"part": 1, "speaker": "Lin Na",       "chinese": "力波，那是谁？",                           "pinyin": "Lìbō, nà shì shéi?",                                        "english": "Libo, who is that?"},
        {"part": 1, "speaker": "Libo",         "chinese": "那是我们老师。",                           "pinyin": "Nà shì wǒmen lǎoshī.",                                      "english": "That is our teacher."},
        {"part": 1, "speaker": "Lin Na",       "chinese": "她是哪国人？",                             "pinyin": "Tā shì nǎ guó rén?",                                        "english": "Which country is she from?"},
        {"part": 1, "speaker": "Libo",         "chinese": "她是中国人。我们老师都是中国人。",         "pinyin": "Tā shì Zhōngguó rén. Wǒmen lǎoshī dōu shì Zhōngguó rén.", "english": "She is Chinese. All our teachers are Chinese."},
        {"part": 2, "speaker": "Libo",         "chinese": "陈老师，您好！这是我哥哥，他是外语老师。","pinyin": "Chén lǎoshī, nín hǎo! Zhè shì wǒ gēge, tā shì wàiyǔ lǎoshī.", "english": "Teacher Chen, hello! This is my elder brother, he is a foreign language teacher."},
        {"part": 2, "speaker": "Teacher Chen", "chinese": "你好！",                                   "pinyin": "Nǐ hǎo!",                                                   "english": "Hello!"},
        {"part": 2, "speaker": "Brother",      "chinese": "你好！",                                   "pinyin": "Nǐ hǎo!",                                                   "english": "Hello!"},
        {"part": 2, "speaker": "Libo",         "chinese": "这是我朋友。",                             "pinyin": "Zhè shì wǒ péngyǒu.",                                       "english": "This is my friend."},
        {"part": 2, "speaker": "Teacher Chen", "chinese": "你好！你也是老师吗？",                     "pinyin": "Nǐ hǎo! Nǐ yě shì lǎoshī ma?",                             "english": "Hello! Are you also a teacher?"},
        {"part": 2, "speaker": "Friend",       "chinese": "您好！我不是老师。我是医生。",             "pinyin": "Nín hǎo! Wǒ bú shì lǎoshī. Wǒ shì yīshēng.",               "english": "Hello! I am not a teacher. I am a doctor."},
        {"part": 2, "speaker": "Teacher Chen", "chinese": "力波，这是你奶奶吗？",                     "pinyin": "Lìbō, zhè shì nǐ nǎinai ma?",                               "english": "Libo, is this your paternal grandmother?"},
        {"part": 2, "speaker": "Libo",         "chinese": "不是，她是我外婆。",                       "pinyin": "Bú shì, tā shì wǒ wàipó.",                                  "english": "No, she is my maternal grandmother."},
        {"part": 2, "speaker": "Libo",         "chinese": "外婆，您好！",                             "pinyin": "Wàipó, nín hǎo!",                                           "english": "Grandmother, hello!"},
        {"part": 2, "speaker": "Grandmother",  "chinese": "你好！",                                   "pinyin": "Nǐ hǎo.",                                                   "english": "Hello!"},
        {"part": 2, "speaker": "Grandmother",  "chinese": "好，坐吧。",                               "pinyin": "Hǎo, zuò ba.",                                              "english": "OK, let's sit."},
    ],
    4: [
        {"part": 1, "speaker": "Lu Yuping",    "chinese": "可以进来吗？",                             "pinyin": "Kěyǐ jìnlái ma?",                                           "english": "May I come in?"},
        {"part": 1, "speaker": "Teacher Yang", "chinese": "请进！",                                   "pinyin": "Qǐng jìn!",                                                 "english": "Please come in!"},
        {"part": 1, "speaker": "Ma Dawei",     "chinese": "杨老师，您好。",                           "pinyin": "Yáng Lǎoshī, nín hǎo.",                                     "english": "Hello, Teacher Yang."},
        {"part": 1, "speaker": "Teacher Yang", "chinese": "你好。",                                   "pinyin": "Nǐ hǎo.",                                                   "english": "Hello."},
        {"part": 1, "speaker": "Ma Dawei",     "chinese": "这是我朋友，他是记者。",                   "pinyin": "Zhè shì wǒ péngyou, tā shì jìzhě.",                         "english": "This is my friend, he is a journalist."},
        {"part": 1, "speaker": "Teacher Yang", "chinese": "请问，您贵姓？",                           "pinyin": "Qǐngwèn, nín guìxìng?",                                     "english": "May I ask, what is your surname?"},
        {"part": 1, "speaker": "Lu Yuping",    "chinese": "我姓陆，叫陆雨平。",                       "pinyin": "Wǒ xìng Lù, jiào Lù Yǔpíng.",                               "english": "My surname is Lu, my name is Lu Yuping."},
        {"part": 1, "speaker": "Teacher Yang", "chinese": "你好，陆先生，认识你很高兴。",             "pinyin": "Nǐ hǎo, Lù xiānsheng, rènshi nǐ hěn gāoxìng.",             "english": "Hello, Mr. Lu, very pleased to meet you."},
        {"part": 1, "speaker": "Lu Yuping",    "chinese": "杨老师，认识您，我也很高兴。",             "pinyin": "Yáng Lǎoshī, rènshi nín, wǒ yě hěn gāoxìng.",              "english": "Teacher Yang, I am also very pleased to meet you."},
        {"part": 2, "speaker": "Lin Na",       "chinese": "你好！我是语言学院的学生，我姓林，叫林娜。我是英国人。你姓什么？", "pinyin": "Nǐ hǎo! Wǒ shì yǔyán xuéyuàn de xuésheng, wǒ xìng Lín, jiào Lín Nà. Wǒ shì Yīngguó rén. Nǐ xìng shénme?", "english": "Hello! I am a student of the Language Institute, my surname is Lin, I am called Lin Na. I am British. What is your surname?"},
        {"part": 2, "speaker": "Ma Dawei",     "chinese": "我姓马，叫马大为。",                       "pinyin": "Wǒ xìng Mǎ, jiào Mǎ Dàwéi.",                                "english": "My surname is Ma, I am called Ma Dawei."},
        {"part": 2, "speaker": "Lin Na",       "chinese": "你是加拿大人吗？",                         "pinyin": "Nǐ shì Jiānádà rén ma?",                                    "english": "Are you Canadian?"},
        {"part": 2, "speaker": "Ma Dawei",     "chinese": "我不是加拿大人，我是美国人，也是语言学院的学生。我学习汉语。", "pinyin": "Wǒ bú shì Jiānádà rén, wǒ shì Měiguó rén, yě shì yǔyán xuéyuàn de xuésheng. Wǒ xuéxí hànyǔ.", "english": "I am not Canadian, I am American and also a student at the Language Institute. I am learning Chinese."},
    ],
    5: [
        {"part": 1, "speaker": "Ma Dawei",  "chinese": "请问，这是王小云的宿舍吗？",             "pinyin": "Qǐngwèn, zhè shì Wáng Xiǎoyún de sùshè ma?",           "english": "Excuse me, is this Wang Xiaoyun's dormitory?"},
        {"part": 1, "speaker": "Roommate",  "chinese": "是。请进，请坐。",                       "pinyin": "Shì. Qǐng jìn, qǐng zuò.",                             "english": "Yes. Please come in, please sit."},
        {"part": 1, "speaker": "Ma Dawei",  "chinese": "谢谢。",                               "pinyin": "Xièxie.",                                               "english": "Thanks."},
        {"part": 1, "speaker": "Ma Dawei",  "chinese": "王小云在吗？",                         "pinyin": "Wáng Xiǎoyún zài ma?",                                 "english": "Is Wang Xiaoyun here?"},
        {"part": 1, "speaker": "Roommate",  "chinese": "她不在。",                             "pinyin": "Tā bú zài.",                                           "english": "She is not here."},
        {"part": 1, "speaker": "Ma Dawei",  "chinese": "她在哪儿？",                           "pinyin": "Tā zài nǎr?",                                          "english": "Where is she?"},
        {"part": 1, "speaker": "Roommate",  "chinese": "对不起，我不知道。",                   "pinyin": "Duìbuqǐ, wǒ bù zhīdào.",                               "english": "Sorry, I don't know."},
        {"part": 1, "speaker": "Ma Dawei",  "chinese": "没关系。好，再见。",                   "pinyin": "Méi guānxi. Hǎo, zàijiàn.",                            "english": "It doesn't matter. OK, see you."},
        {"part": 1, "speaker": "Roommate",  "chinese": "再见。",                               "pinyin": "Zàijiàn.",                                             "english": "See you."},
        {"part": 2, "speaker": "Lin Na",    "chinese": "小姐，请问餐厅在哪儿？",               "pinyin": "Xiǎojiě, qǐngwèn cāntīng zài nǎr?",                   "english": "Miss, excuse me, where is the cafeteria?"},
        {"part": 2, "speaker": "Staff",     "chinese": "在二层二零四号。",                     "pinyin": "Zài èr céng èr líng sì hào.",                          "english": "On the second floor, number 204."},
        {"part": 2, "speaker": "Lin Na",    "chinese": "谢谢。",                               "pinyin": "Xièxie.",                                              "english": "Thanks."},
        {"part": 2, "speaker": "Staff",     "chinese": "不用谢。",                             "pinyin": "Bú yòng xiè.",                                         "english": "You're welcome."},
        {"part": 2, "speaker": "Lin Na",    "chinese": "大为，我们在这儿。",                   "pinyin": "Dàwéi, wǒmen zài zhèr.",                               "english": "Dawei, we are over here."},
        {"part": 2, "speaker": "Ma Dawei",  "chinese": "对不起，我来晚了。",                   "pinyin": "Duìbuqǐ, wǒ lái wǎn le.",                              "english": "Sorry, I've come late."},
        {"part": 2, "speaker": "Lin Na",    "chinese": "没关系。",                             "pinyin": "Méiguānxi.",                                           "english": "No problem."},
    ],
    6: [
        {"part": 1, "speaker": "Wang Xiaoyun", "chinese": "谢谢。林娜，昨天的京剧怎么样？",               "pinyin": "Xièxie. Lín Nà, zuótiān de jīngjù zěnme yàng?",      "english": "Thanks. Lin Na, how was yesterday's Beijing Opera?"},
        {"part": 1, "speaker": "Lin Na",       "chinese": "很有意思。今天天气很好，我们去游泳，好吗？",   "pinyin": "Hěn yǒuyìsi. Jīntiān tiānqì hěn hǎo, wǒmen qù yóuyǒng, hǎo ma?", "english": "Very interesting. The weather is good today, shall we go swimming?"},
        {"part": 1, "speaker": "Wang Xiaoyun", "chinese": "太好了！什么时候去？",                         "pinyin": "Tài hǎo le! Shénme shíhòu qù?",                       "english": "That's great! When are we going?"},
        {"part": 1, "speaker": "Lin Na",       "chinese": "现在去可以吗？",                               "pinyin": "Xiànzài qù kěyǐ ma?",                                 "english": "How about going now?"},
        {"part": 1, "speaker": "Wang Xiaoyun", "chinese": "可以。",                                       "pinyin": "Kěyǐ.",                                               "english": "OK."},
        {"part": 2, "speaker": "Libo",         "chinese": "杨老师，明天您有时间吗？",                     "pinyin": "Yáng Lǎoshī, míngtiān nín yǒu shíjiān ma?",           "english": "Teacher Yang, do you have time tomorrow?"},
        {"part": 2, "speaker": "Teacher Yang", "chinese": "对不起，请再说一遍。",                         "pinyin": "Duìbuqǐ, qǐng zài shuō yí biàn.",                     "english": "Sorry, could you say that again?"},
        {"part": 2, "speaker": "Libo",         "chinese": "明天您有时间吗？我们去打球，好吗？",           "pinyin": "Míngtiān nín yǒu shíjiān ma? Wǒmen qù dǎqiú, hǎo ma?", "english": "Do you have time tomorrow? How about we go play ball?"},
        {"part": 2, "speaker": "Teacher Yang", "chinese": "很抱歉，明天我很忙，恐怕不行。谢谢你们。",     "pinyin": "Hěn bàoqiàn, míngtiān wǒ hěn máng, kǒngpà bùxíng. Xièxie nǐmen.", "english": "Very sorry, I will be very busy tomorrow, I am afraid I cannot. Thank you, though."},
    ],
    7: [
        {"part": 1, "speaker": "Lin Na",         "chinese": "力波，明天开学，我很高兴。你看，他是不是我们学院的老师？", "pinyin": "Lìbō, míngtiān kāixué, wǒ hěn gāoxìng. Nǐ kàn, tā shì bu shì wǒmen xuéyuàn de lǎoshī?", "english": "Libo, school opens tomorrow, I'm very happy. Look, isn't he a teacher from our institute?"},
        {"part": 1, "speaker": "Libo",           "chinese": "我问一下。请问，您是我们学院的老师吗？",           "pinyin": "Wǒ wèn yíxià. Qǐngwèn, nín shì wǒmen xuéyuàn de lǎoshī ma?", "english": "Let me ask. Excuse me, are you a teacher of our institute?"},
        {"part": 1, "speaker": "Prof. Zhang",    "chinese": "是，我是语言学院的老师。",                         "pinyin": "Shì, wǒ shì yǔyán xuéyuàn de lǎoshī.",             "english": "Yes, I am a teacher of the Institute of Languages."},
        {"part": 1, "speaker": "Libo",           "chinese": "您贵姓？",                                         "pinyin": "Nín guìxìng?",                                      "english": "What is your surname?"},
        {"part": 1, "speaker": "Prof. Zhang",    "chinese": "我姓张，我们认识一下，这是我的名片。",             "pinyin": "Wǒ xìng Zhāng, wǒmen rènshi yíxià, zhè shì wǒ de míngpiàn.", "english": "My surname is Zhang. Let's get to know each other — this is my name card."},
        {"part": 1, "speaker": "Libo",           "chinese": "谢谢。啊，您是张教授。我叫丁力波，她叫林娜。我们都是语言学院的学生。", "pinyin": "Xièxie. À, nín shì Zhāng jiàoshòu. Wǒ jiào Dīng Lìbō, tā jiào Lín Nà. Wǒmen dōu shì yǔyán xuéyuàn de xuésheng.", "english": "Thanks. Ah, you are Professor Zhang. I am Ding Libo, she is Lin Na. We are both students at the Institute of Languages."},
        {"part": 1, "speaker": "Lin Na",         "chinese": "您是语言学院的教授，认识您，我们很高兴。",         "pinyin": "Nín shì yǔyán xuéyuàn de jiàoshòu, rènshi nín, wǒmen hěn gāoxìng.", "english": "You are a Professor from the Institute of Languages, we are very pleased to meet you."},
        {"part": 1, "speaker": "Prof. Zhang",    "chinese": "认识你们，我也很高兴。你们都好吗？",               "pinyin": "Rènshi nǐmen, wǒ yě hěn gāoxìng. Nǐmen dōu hǎo ma?", "english": "I am also very pleased to meet you. How are you both?"},
        {"part": 1, "speaker": "Libo",           "chinese": "谢谢，我们都很好。张教授，您忙不忙？",             "pinyin": "Xièxie, wǒmen dōu hěn hǎo. Zhāng jiàoshòu, nín máng bu máng?", "english": "Thanks, we are both fine. Professor Zhang, are you busy?"},
        {"part": 1, "speaker": "Prof. Zhang",    "chinese": "我很忙。好，你们请坐，再见！",                     "pinyin": "Wǒ hěn máng. Hǎo, nǐmen qǐng zuò, zàijiàn!",       "english": "I am very busy. Okay, please sit, goodbye!"},
        {"part": 1, "speaker": "Lin Na",         "chinese": "再见！",                                           "pinyin": "Zàijiàn!",                                          "english": "Goodbye!"},
        {"part": 2, "speaker": "Lin Na",         "chinese": "唉，这边儿。",                                     "pinyin": "Āi, zhè biānr.",                                    "english": "Hey, over here."},
        {"part": 2, "speaker": "Libo",           "chinese": "林娜，那是谁？",                                   "pinyin": "Lín Nà, nà shì sheí?",                              "english": "Lin Na, who is that?"},
        {"part": 2, "speaker": "Lin Na",         "chinese": "那是马大为。你认识不认识他？",                     "pinyin": "Nà shì Mǎ Dàwéi. Nǐ rènshi bu rènshi tā?",         "english": "That is Ma Dawei. Do you know him?"},
        {"part": 2, "speaker": "Libo",           "chinese": "我不认识他。",                                     "pinyin": "Wǒ bú rènshi tā.",                                  "english": "I don't know him."},
        {"part": 2, "speaker": "Lin Na",         "chinese": "我来介绍一下。你好，大为，这是我朋友。",           "pinyin": "Wǒ lái jièshào yíxià. Nǐ hǎo, Dàwéi, zhè shì wǒ péngyǒu.", "english": "Let me introduce you. Hello, Dawei, this is my friend."},
        {"part": 2, "speaker": "Libo",           "chinese": "你好！我姓丁，叫丁力波。请问，你叫什么名字？",     "pinyin": "Nǐ hǎo! Wǒ xìng Dīng, jiào Dīng Lìbō. Qǐngwèn, nǐ jiào shénme míngzi?", "english": "Hello! My surname is Ding, I am called Ding Libo. May I ask, what is your name?"},
        {"part": 2, "speaker": "Ma Dawei",       "chinese": "我的中文名字叫马大为。你是不是中国人？",           "pinyin": "Wǒ de zhōngwén míngzi jiào Mǎ Dàwéi. Nǐ shì bu shì Zhōngguó rén?", "english": "My Chinese name is Ma Dawei. Are you Chinese?"},
        {"part": 2, "speaker": "Libo",           "chinese": "我是加拿大人。我妈妈是中国人，我爸爸是加拿大人。你也是加拿大人吗？", "pinyin": "Wǒ shì Jiānádà rén. Wǒ māma shì Zhōngguó rén, wǒ bàba shì Jiānádà rén. Nǐ yě shì Jiānádà rén ma?", "english": "I am Canadian. My mother is Chinese, my father is Canadian. Are you also Canadian?"},
        {"part": 2, "speaker": "Ma Dawei",       "chinese": "不是，我不是加拿大人，我是美国人。你学习什么专业？", "pinyin": "Bú shì, wǒ bú shì Jiānádà rén, wǒ shì Měiguó rén. Nǐ xuéxí shénme zhuānyè?", "english": "No, I am not Canadian, I am American. What major are you studying?"},
        {"part": 2, "speaker": "Libo",           "chinese": "我学习美术专业。你呢？",                           "pinyin": "Wǒ xuéxí měishù zhuānyè. Nǐ ne?",                   "english": "I am an art major. And you?"},
        {"part": 2, "speaker": "Ma Dawei",       "chinese": "我学习文学专业。现在我学习汉语。",                 "pinyin": "Wǒ xuéxí wénxué zhuānyè. Xiànzài wǒ xuéxí hànyǔ.", "english": "My major is literature. At the moment I am learning Chinese."},
        {"part": 2, "speaker": "Libo",           "chinese": "现在我们都学习汉语，也都是汉语系的学生。",         "pinyin": "Xiànzài wǒmen dōu xuéxí hànyǔ, yě dōu shì hànyǔxì de xuésheng.", "english": "Now we are all learning Chinese, and all are students in the Department of Chinese."},
    ],
    8: [
        {"part": 1, "speaker": "Libo",     "chinese": "这是不是你们家的照片？",                       "pinyin": "Zhè shì bu shì nǐmen jiā de zhàopiàn?",                 "english": "Is this a photograph of your family?"},
        {"part": 1, "speaker": "Lin Na",   "chinese": "是啊。",                                       "pinyin": "Shì a.",                                                "english": "Yes, it is."},
        {"part": 1, "speaker": "Libo",     "chinese": "我看一下。你们家有几口人？",                   "pinyin": "Wǒ kàn yíxià. Nǐmen jiā yǒu jǐ kǒu rén?",             "english": "Let me have a look. How many people are there in your family?"},
        {"part": 1, "speaker": "Lin Na",   "chinese": "我们家有四口人。这是我爸爸，我妈妈，这是我哥哥和我。你们家呢？", "pinyin": "Wǒmen jiā yǒu sì kǒu rén. Zhè shì wǒ bàba, wǒ māma, zhè shì wǒ gēge hé wǒ. Nǐmen jiā ne?", "english": "There are four people in my family. This is my father, my mother, this is my elder brother and me. How about your family?"},
        {"part": 1, "speaker": "Libo",     "chinese": "我有妈妈，有一个姐姐和两个弟弟。我们家一共有六口人。", "pinyin": "Wǒ yǒu māma, yǒu yí ge jiějie hé liǎng ge dìdi. Wǒmen jiā yígòng yǒu liù kǒu rén.", "english": "I have a mother, an older sister and two younger brothers. In total, our family has six people."},
        {"part": 1, "speaker": "Lin Na",   "chinese": "这是五口人，还有谁？",                         "pinyin": "Zhè shì wǔ kǒu rén, hái yǒu sheí?",                    "english": "That is five people. Who else is there?"},
        {"part": 1, "speaker": "Libo",     "chinese": "还有贝贝。",                                   "pinyin": "Hái yǒu Bèibèi.",                                       "english": "There is also Beibei!"},
        {"part": 1, "speaker": "Lin Na",   "chinese": "贝贝是你妹妹吗？",                             "pinyin": "Bèibèi shì nǐ mèimei ma?",                              "english": "Is Beibei your younger sister?"},
        {"part": 1, "speaker": "Libo",     "chinese": "不，贝贝是我的小狗。",                         "pinyin": "Bù, Bèibèi shì wǒ de xiǎo gǒu.",                       "english": "No, Beibei is my little dog."},
        {"part": 1, "speaker": "Lin Na",   "chinese": "小狗也是一口人吗？",                           "pinyin": "Xiǎo gǒu yě shì yì kǒu rén ma?",                       "english": "Is a little dog also a family member?"},
        {"part": 1, "speaker": "Libo",     "chinese": "贝贝是我们的好朋友，当然是我们家的人。我有一张贝贝的照片，你看。", "pinyin": "Bèibèi shì wǒmen de hǎo péngyǒu, dāngrán shì wǒmen jiā de rén. Wǒ yǒu yì zhāng Bèibèi de zhàopiàn, nǐ kàn.", "english": "Beibei is our good friend, of course he is a family member. I have a photograph of Beibei, take a look."},
        {"part": 1, "speaker": "Lin Na",   "chinese": "哇！真可爱。",                                 "pinyin": "Wa! Zhēn kě'ài.",                                       "english": "Wow! So cute."},
        {"part": 1, "speaker": "Libo",     "chinese": "你们家有小狗吗？",                             "pinyin": "Nǐmen jiā yǒu xiǎo gǒu ma?",                           "english": "Does your family have a little dog?"},
        {"part": 1, "speaker": "Lin Na",   "chinese": "我们家没有小狗。",                             "pinyin": "Wǒmen jiā méiyǒu xiǎo gǒu.",                           "english": "Our family does not have a little dog."},
        {"part": 1, "speaker": "Libo",     "chinese": "林娜，你有没有男朋友？",                       "pinyin": "Lín Nà, nǐ yǒu méiyǒu nán péngyou?",                   "english": "Lin Na, do you have a boyfriend?"},
        {"part": 1, "speaker": "Lin Na",   "chinese": "我有男朋友。",                                 "pinyin": "Wǒ yǒu nán péngyou.",                                   "english": "I have a boyfriend."},
        {"part": 1, "speaker": "Libo",     "chinese": "他做什么工作？",                               "pinyin": "Tā zuò shénme gōngzuò?",                                "english": "What work does he do?"},
        {"part": 1, "speaker": "Lin Na",   "chinese": "他是医生。",                                   "pinyin": "Tā shì yīshēng.",                                       "english": "He is a doctor."},
        {"part": 2, "speaker": "Lin Na",   "chinese": "语言学院大不大？",                             "pinyin": "Yǔyán xuéyuàn dà bu dà?",                              "english": "Is the Institute of Languages big?"},
        {"part": 2, "speaker": "Libo",     "chinese": "不太大。",                                     "pinyin": "Bú tài dà.",                                           "english": "Not too big."},
        {"part": 2, "speaker": "Lin Na",   "chinese": "语言学院有多少个系？",                         "pinyin": "Yǔyán xuéyuàn yǒu duōshao ge xì?",                    "english": "How many departments are there in the Institute of Languages?"},
        {"part": 2, "speaker": "Libo",     "chinese": "有十二个系。",                                 "pinyin": "Yǒu shí'èr ge xì.",                                    "english": "There are twelve departments."},
        {"part": 2, "speaker": "Lin Na",   "chinese": "你喜欢你们外语系吗？",                         "pinyin": "Nǐ xǐhuān nǐmen wàiyǔ xì ma?",                         "english": "Do you like your Foreign Languages department?"},
        {"part": 2, "speaker": "Libo",     "chinese": "我很喜欢外语系。",                             "pinyin": "Wǒ hěn xǐhuān wàiyǔ xì.",                              "english": "I like the Foreign Languages department."},
        {"part": 2, "speaker": "Lin Na",   "chinese": "你们外语系有多少老师？",                       "pinyin": "Nǐmen wàiyǔ xì yǒu duōshao lǎoshī?",                  "english": "How many teachers are there in your Foreign Languages department?"},
        {"part": 2, "speaker": "Libo",     "chinese": "外语系有二十八个中国老师，十一个外国老师。你们系呢？", "pinyin": "Wàiyǔ xì yǒu èrshíbā ge Zhōngguó lǎoshī, shíyī ge wàiguó lǎoshī. Nǐmen xì ne?", "english": "The Foreign Languages department has 28 Chinese teachers and eleven foreign teachers. How about your department?"},
        {"part": 2, "speaker": "Lin Na",   "chinese": "我们汉语系很大。我们系的老师也很多，有一百个，他们都是中国人。我们系没有外国老师。", "pinyin": "Wǒmen hànyǔ xì hěn dà. Wǒmen xì de lǎoshī yě hěnduō, yǒu yìbǎi ge, tāmen dōu shì Zhōngguó rén. Wǒmen xì méiyǒu wàiguó lǎoshī.", "english": "Our Chinese Language department is very big. We have many teachers, there are one hundred of them, and they are all Chinese. Our department does not have any foreign teachers."},
    ],
    9: [
        {"part": 1, "speaker": "Wang Xiaoyun", "chinese": "林娜，你怎么样？忙不忙？",                   "pinyin": "Lín Nà, nǐ zěnme yàng? Máng bu máng?",               "english": "Lin Na, how are you? Are you busy?"},
        {"part": 1, "speaker": "Lin Na",       "chinese": "我今天很忙。",                               "pinyin": "Wǒ jīntiān hěn máng.",                                "english": "I'm very busy today."},
        {"part": 1, "speaker": "Wang Xiaoyun", "chinese": "明天上午你有没有课？",                       "pinyin": "Míngtiān shàngwǔ nǐ yǒu méiyǒu kè?",                 "english": "Do you have class tomorrow morning?"},
        {"part": 1, "speaker": "Lin Na",       "chinese": "明天是星期几？",                             "pinyin": "Míngtiān shì xīngqī jǐ?",                             "english": "What is the day tomorrow?"},
        {"part": 1, "speaker": "Wang Xiaoyun", "chinese": "明天是星期四。",                             "pinyin": "Míngtiān shì xīngqīsì.",                              "english": "Tomorrow is Thursday."},
        {"part": 1, "speaker": "Lin Na",       "chinese": "我上午，下午都有课。",                       "pinyin": "Wǒ shàngwǔ, xiàwǔ dōu yǒu kè.",                      "english": "I have classes both in the morning and in the afternoon."},
        {"part": 1, "speaker": "Wang Xiaoyun", "chinese": "你星期日有时间吗？",                         "pinyin": "Nǐ xīngqīrì yǒu shíjiān ma?",                         "english": "Do you have time on Sunday?"},
        {"part": 1, "speaker": "Lin Na",       "chinese": "星期日是几号？",                             "pinyin": "Xīngqīrì shì jǐ hào?",                                "english": "What is the date on Sunday?"},
        {"part": 1, "speaker": "Wang Xiaoyun", "chinese": "星期日是十月二十七号，是宋华的生日。",       "pinyin": "Xīngqīrì shì shí yuè èrshíqī hào, shì Sòng Huá de shēngrì.", "english": "Sunday is the 27th of October, it's Song Hua's birthday."},
        {"part": 1, "speaker": "Lin Na",       "chinese": "是吗？他今年多大？",                         "pinyin": "Shì ma? Tā jīnnián duōdà?",                           "english": "Really? How old is he this year?"},
        {"part": 1, "speaker": "Wang Xiaoyun", "chinese": "宋华一九八二年十月二十七日出生，属狗。他今年二十岁。", "pinyin": "Sòng Huá yījiǔbā'èr nián shí yuè èrshíqī rì chūshēng, shǔ gǒu. Tā jīnnián èrshí suì.", "english": "Song Hua was born on the 27th of October 1982, year of the dog. This year he is 20 years old."},
        {"part": 1, "speaker": "Lin Na",       "chinese": "他是哪儿人？",                               "pinyin": "Tā shì nǎr rén?",                                     "english": "Where is he from?"},
        {"part": 1, "speaker": "Wang Xiaoyun", "chinese": "他是北京人。他爸爸，妈妈都在北京。星期日下午我们有一个聚会，祝贺他的生日。力波，大为都去，你参加不参加？", "pinyin": "Tā shì Běijīng rén. Tā bàba, māma dōu zài Běijīng. Xīngqīrì xiàwǔ wǒmen yǒu yígè jùhuì, zhùhè tā de shēngrì. Lìbō, Dàwéi dōu qù, nǐ cānjiā bu cānjiā?", "english": "He is from Beijing. His father and mother are both in Beijing. We are holding a party on Sunday afternoon to celebrate his birthday. Libo and Dawei are both going — will you join?"},
        {"part": 1, "speaker": "Lin Na",       "chinese": "太好了！我当然参加。中国人生日吃蛋糕吗？",   "pinyin": "Tài hǎole! Wǒ dāngrán cānjiā. Zhōngguó rén shēngrì chī dàngāo ma?", "english": "That's great! Of course I'll join. Do Chinese people eat cake on their birthday?"},
        {"part": 1, "speaker": "Wang Xiaoyun", "chinese": "吃蛋糕。",                                   "pinyin": "Chī dàngāo.",                                         "english": "Yes, we do."},
        {"part": 1, "speaker": "Lin Na",       "chinese": "我买一个大蛋糕，好吗？",                     "pinyin": "Wǒ mǎi yígè dà dàngāo, hǎo ma?",                     "english": "How about I buy a big cake then?"},
        {"part": 1, "speaker": "Wang Xiaoyun", "chinese": "好啊。我买两瓶红葡萄酒。",                   "pinyin": "Hǎo a. Wǒ mǎi liǎng píng hóng pútáojiǔ.",           "english": "Sounds good. I'll buy two bottles of red wine."},
        {"part": 2, "speaker": "Lin Na",       "chinese": "嗨！你们好！",                               "pinyin": "Hāi! Nǐmen hǎo!",                                     "english": "Hi! Hello everybody!"},
        {"part": 2, "speaker": "Friends",      "chinese": "你们好！",                                   "pinyin": "Nǐmen hǎo!",                                          "english": "Hello!"},
        {"part": 2, "speaker": "Lin Na",       "chinese": "宋华，这是生日蛋糕。祝你生日快乐！",         "pinyin": "Sòng Huá, zhè shì shēngrì dàngāo. Zhù nǐ shēngrì kuàilè!", "english": "Song Hua, this is the birthday cake. Happy birthday!"},
        {"part": 2, "speaker": "Song Hua",     "chinese": "谢谢。请坐，请坐。蛋糕真漂亮。你们来，我很高兴。", "pinyin": "Xièxie. Qǐng zuò, qǐng zuò. Dàngāo zhēn piàoliang. Nǐmen lái, wǒ hěn gāoxìng.", "english": "Thank you. Please sit. The cake is really beautiful. I'm very happy you all came."},
        {"part": 2, "speaker": "Song Hua",     "chinese": "今天我们吃北京烤鸭。我很喜欢吃烤鸭。",       "pinyin": "Jīntiān wǒmen chī Běijīng kǎoyā. Wǒ hěn xǐhuān chī kǎoyā.", "english": "Today we are going to eat Beijing roast duck. I like eating roast duck very much."},
        {"part": 2, "speaker": "Lin Na",       "chinese": "我们喝什么酒？",                             "pinyin": "Wǒmen hē shénme jiǔ?",                                "english": "What shall we drink?"},
        {"part": 2, "speaker": "Song Hua",     "chinese": "当然喝红葡萄酒，我们还吃寿面。",             "pinyin": "Dāngrán hē hóng pútáojiǔ, wǒmen hái chī shòumiàn.", "english": "Of course we will drink red wine, and we are also eating longevity noodles!"},
        {"part": 2, "speaker": "Lin Na",       "chinese": "吃寿面？真有意思。",                         "pinyin": "Chī shòumiàn? Zhēn yǒuyìsi.",                         "english": "Eat longevity noodles? Really interesting."},
        {"part": 2, "speaker": "Song Hua",     "chinese": "林娜，你的生日是哪天？",                     "pinyin": "Lín Nà, nǐ de shēngrì shì nǎ tiān?",                 "english": "Lin Na, when is your birthday?"},
        {"part": 2, "speaker": "Lin Na",       "chinese": "十一月，十二号。",                           "pinyin": "Shíyī yuè, shí'èr hào.",                              "english": "12th November."},
        {"part": 2, "speaker": "Song Hua",     "chinese": "好，十一月，十二号我们再来吃寿面。",         "pinyin": "Hǎo, shíyī yuè, shí'èr hào wǒmen zàilái chī shòumiàn.", "english": "OK, on the 12th of November we will again eat longevity noodles!"},
    ],
    10: [
        {"part": 1, "speaker": "Libo",      "chinese": "大为！",                                       "pinyin": "Dàwéi!",                                              "english": "Dawei!"},
        {"part": 1, "speaker": "Ma Dawei",  "chinese": "诶！",                                         "pinyin": "Éi!",                                                 "english": "Hey!"},
        {"part": 1, "speaker": "Libo",      "chinese": "你在这儿买什么？",                             "pinyin": "Nǐ zài zhèr mǎi shénme?",                             "english": "What are you buying here?"},
        {"part": 1, "speaker": "Ma Dawei",  "chinese": "我买音乐光盘。",                               "pinyin": "Wǒ mǎi yīnyuè guāngpán.",                             "english": "I'm buying music CDs."},
        {"part": 1, "speaker": "Libo",      "chinese": "你常常来这儿吗？",                             "pinyin": "Nǐ chángcháng lái zhèr ma?",                          "english": "Do you come here often?"},
        {"part": 1, "speaker": "Ma Dawei",  "chinese": "我不常来这儿。星期天我常常跟林娜去小商场。",   "pinyin": "Wǒ bù cháng lái zhèr. Xīngqītiān wǒ chángcháng gēn Lín Nà qù xiǎo shāngchǎng.", "english": "I don't come here often. On Sundays I usually go to the small shopping malls with Lin Na."},
        {"part": 1, "speaker": "Libo",      "chinese": "哦……",                                        "pinyin": "Ò……",                                                 "english": "Oh…"},
        {"part": 1, "speaker": "Ma Dawei",  "chinese": "这个商场很大。",                               "pinyin": "Zhège shāngchǎng hěn dà.",                            "english": "This shopping mall is very big."},
        {"part": 1, "speaker": "Libo",      "chinese": "你喜欢什么音乐？",                             "pinyin": "Nǐ xǐhuān shénme yīnyuè?",                            "english": "What kind of music do you like?"},
        {"part": 1, "speaker": "Ma Dawei",  "chinese": "我喜欢中国音乐。",                             "pinyin": "Wǒ xǐhuān Zhōngguó yīnyuè.",                          "english": "I like Chinese music."},
        {"part": 1, "speaker": "Libo",      "chinese": "哦……",                                        "pinyin": "Ò……",                                                 "english": "Oh…"},
        {"part": 1, "speaker": "Ma Dawei",  "chinese": "这张光盘怎么样？",                             "pinyin": "Zhè zhāng guāngpán zěnme yàng?",                      "english": "How is this CD?"},
        {"part": 1, "speaker": "Libo",      "chinese": "这张很好，是《梁祝》，很有名。",               "pinyin": "Zhè zhāng hěn hǎo, shì 《Liáng Zhù》, hěn yǒumíng.", "english": "This one is very good, it's 'Butterfly Lovers', very famous."},
        {"part": 1, "speaker": "Ma Dawei",  "chinese": "好，我买这张。这儿有没有书和报？",             "pinyin": "Hǎo, wǒ mǎi zhè zhāng. Zhèr yǒu méiyǒu shū hé bào?", "english": "Great, I'll buy this one. Are there any books or newspapers here?"},
        {"part": 1, "speaker": "Libo",      "chinese": "这儿没有书，也没有报。",                       "pinyin": "Zhèr méiyǒu shū, yě méiyǒu bào.",                     "english": "There are no books here, nor any newspapers."},
        {"part": 1, "speaker": "Ma Dawei",  "chinese": "本子呢？",                                     "pinyin": "Běnzi ne?",                                           "english": "How about notebooks?"},
        {"part": 1, "speaker": "Libo",      "chinese": "有，在那儿买。跟我来，我也买本子。",           "pinyin": "Yǒu, zài nàr mǎi. Gēn wǒ lái, wǒ yě mǎi běnzi.",   "english": "Yes, you can buy there. Come with me, I am also buying notebooks."},
        {"part": 2, "speaker": "Vendor",    "chinese": "先生，您要什么？",                             "pinyin": "Xiānsheng, nín yào shénme?",                          "english": "Sir, what do you want?"},
        {"part": 2, "speaker": "Ma Dawei",  "chinese": "你好，师傅。请问，这是什么？",                 "pinyin": "Nǐ hǎo, shīfu. Qǐngwèn, zhè shì shénme?",            "english": "Hello. Excuse me, what is this?"},
        {"part": 2, "speaker": "Vendor",    "chinese": "您不认识吗？这是香蕉苹果。",                   "pinyin": "Nín bú rènshi ma? Zhè shì xiāngjiāo píngguǒ.",       "english": "You don't recognise it? This is a banana-apple."},
        {"part": 2, "speaker": "Ma Dawei",  "chinese": "对不起，我是问：这个汉语怎么说？",             "pinyin": "Duìbuqǐ, wǒ shì wèn: zhège hànyǔ zěnme shuō?",       "english": "Sorry, I am asking: what is this called in Chinese?"},
        {"part": 2, "speaker": "Vendor",    "chinese": "啊，您是外国人。您在哪儿工作？",               "pinyin": "À, nín shì wàiguó rén. Nín zài nǎr gōngzuò?",        "english": "Ah, you are a foreigner. Where do you work?"},
        {"part": 2, "speaker": "Ma Dawei",  "chinese": "我在语言学院学习。",                           "pinyin": "Wǒ zài yǔyán xuéyuàn xuéxí.",                         "english": "I am a student at the Institute of Languages."},
        {"part": 2, "speaker": "Vendor",    "chinese": "您学习汉语，是不是？您跟我学，很容易：这叫香蕉，这叫香蕉苹果，这也是苹果，那是葡萄……", "pinyin": "Nín xuéxí hànyǔ, shì bu shì? Nín gēn wǒ xué, hěn róngyì: zhè jiào xiāngjiāo, zhè jiào xiāngjiāo píngguǒ, zhè yě shì píngguǒ, nà shì pútao……", "english": "You're studying Chinese, right? I'll teach you, very easy: this is called a banana, this is called a banana-apple, this is also an apple, those are grapes…"},
        {"part": 2, "speaker": "Ma Dawei",  "chinese": "香蕉，苹果，香蕉苹果……一斤苹果多少钱？",     "pinyin": "Xiāngjiāo, píngguǒ, xiāngjiāo píngguǒ……yì jīn píngguǒ duōshao qián?", "english": "Banana, apple, banana-apple… how much is one jin of apples?"},
        {"part": 2, "speaker": "Vendor",    "chinese": "一斤三块二毛钱。",                             "pinyin": "Yì jīn sān kuài èr máo qián.",                        "english": "One jin is 3 yuan and 20 mao."},
        {"part": 2, "speaker": "Ma Dawei",  "chinese": "您的苹果真贵。",                               "pinyin": "Nín de píngguǒ zhēn guì.",                             "english": "Your apples are really expensive."},
        {"part": 2, "speaker": "Vendor",    "chinese": "一斤三块二不贵。您看，我的苹果大。好，做个朋友，三块钱一斤。", "pinyin": "Yì jīn sān kuài èr bú guì. Nín kàn, wǒ de píngguǒ dà. Hǎo, zuò ge péngyou, sān kuài qián yì jīn.", "english": "One jin for 3.20 is not expensive. Look, my apples are very big. All right, let's be friends — 3 yuan for one jin."},
        {"part": 2, "speaker": "Ma Dawei",  "chinese": "一斤香蕉多少钱？",                             "pinyin": "Yì jīn xiāngjiāo duōshao qián?",                      "english": "How much is one jin of bananas?"},
        {"part": 2, "speaker": "Vendor",    "chinese": "两块七毛五分一斤，五块钱两斤。",               "pinyin": "Liǎng kuài qī máo wǔ fēn yì jīn, wǔ kuài qián liǎng jīn.", "english": "2.75 yuan for one jin, 5 yuan for two jin."},
        {"part": 2, "speaker": "Ma Dawei",  "chinese": "我买三斤香蕉和两斤香蕉苹果。",                 "pinyin": "Wǒ mǎi sān jīn xiāngjiāo hé liǎng jīn xiāngjiāo píngguǒ.", "english": "I'll buy 3 jin of bananas and 2 jin of banana-apples."},
        {"part": 2, "speaker": "Vendor",    "chinese": "一共十四块钱。再送您一个苹果。您还要什么？",   "pinyin": "Yígòng shísì kuài qián. Zài sòng nín yígè píngguǒ. Nín hái yào shénme?", "english": "Altogether 14 yuan. I'll give you one more apple. Would you like anything else?"},
        {"part": 2, "speaker": "Ma Dawei",  "chinese": "不要了，谢谢。给你钱。",                       "pinyin": "Bú yào le, xièxie. Gěi nǐ qián.",                    "english": "No, thanks. Here's your money."},
        {"part": 2, "speaker": "Vendor",    "chinese": "好，您给我二十块钱，我找您六块钱。再见。",     "pinyin": "Hǎo, nín gěi wǒ èrshí kuài qián, wǒ zhǎo nín liù kuài qián. Zàijiàn.", "english": "OK, you gave me 20 yuan, I'll give you 6 yuan change. Goodbye."},
        {"part": 2, "speaker": "Ma Dawei",  "chinese": "再见！",                                       "pinyin": "Zàijiàn!",                                            "english": "Goodbye!"},
    ],
    11: [
        {"part": 1, "speaker": "Driver",   "chinese": "小姐，您去哪儿？",                             "pinyin": "Xiǎojiě, nín qù nǎr?",                               "english": "Miss, where are you going?"},
        {"part": 1, "speaker": "Lin Na",   "chinese": "我去语言学院。",                               "pinyin": "Wǒ qù yǔyán xuéyuàn.",                                "english": "I'm going to the Institute of Languages."},
        {"part": 1, "speaker": "Driver",   "chinese": "好。",                                         "pinyin": "Hǎo.",                                                "english": "OK."},
        {"part": 1, "speaker": "Lin Na",   "chinese": "师傅，请问现在几点？",                         "pinyin": "Shīfu, qǐngwèn xiànzài jǐ diǎn?",                    "english": "Driver, may I ask what time it is now?"},
        {"part": 1, "speaker": "Driver",   "chinese": "差一刻八点。您会说汉语啊！",                   "pinyin": "Chà yíkè bā diǎn. Nín huì shuō hànyǔ a!",           "english": "Quarter-to-eight. You can speak Chinese!"},
        {"part": 1, "speaker": "Lin Na",   "chinese": "我会说一点儿汉语。我是学生，现在回学院上课。", "pinyin": "Wǒ huì shuō yìdiǎnr hànyǔ. Wǒ shì xuésheng, xiànzài huí xuéyuàn shàngkè.", "english": "I can speak a little Chinese. I am a student, returning to campus for class now."},
        {"part": 1, "speaker": "Driver",   "chinese": "你们几点上课？",                               "pinyin": "Nǐmen jǐ diǎn shàngkè?",                              "english": "What time is your class?"},
        {"part": 1, "speaker": "Lin Na",   "chinese": "八点上课。师傅，我们八点能到吗？",             "pinyin": "Bā diǎn shàngkè. Shīfu, wǒmen bā diǎn néng dào ma?", "english": "Eight o'clock. Driver, can we arrive by eight?"},
        {"part": 1, "speaker": "Driver",   "chinese": "能到。您的汉语很好。",                         "pinyin": "Néng dào. Nín de hànyǔ hěn hǎo.",                    "english": "Yes. Your Chinese is very good."},
        {"part": 1, "speaker": "Lin Na",   "chinese": "哪里，我的汉语不太好。您会不会说英语？",       "pinyin": "Nǎlǐ, wǒ de hànyǔ bú tài hǎo. Nín huì bu huì shuō yīngyǔ?", "english": "You flatter me, my Chinese is not that good. Can you speak English?"},
        {"part": 1, "speaker": "Driver",   "chinese": "我不会说英语。我也喜欢外语，常常在家学点儿英语。", "pinyin": "Wǒ bú huì shuō yīngyǔ. Wǒ yě xǐhuan wàiyǔ, chángcháng zàijiā xué diǎnr yīngyǔ.", "english": "I cannot speak English. I also like foreign languages, at home I often study a little English."},
        {"part": 1, "speaker": "Lin Na",   "chinese": "谁教你英语？",                                 "pinyin": "Sheí jiāo nǐ yīngyǔ?",                                "english": "Who teaches you English?"},
        {"part": 1, "speaker": "Driver",   "chinese": "我孙女儿。",                                   "pinyin": "Wǒ sūn nǚ'ér.",                                       "english": "My granddaughter."},
        {"part": 1, "speaker": "Lin Na",   "chinese": "真有意思。她今年几岁？",                       "pinyin": "Zhēn yǒuyìsi. Tā jīnnián jǐ suì?",                   "english": "Really interesting. How old is she this year?"},
        {"part": 1, "speaker": "Driver",   "chinese": "六岁。我的岁数太大了，学英语不容易。",         "pinyin": "Liù suì. Wǒ de suìshu tài dà le, xué yīngyǔ bù róngyì.", "english": "Six years old. I am too old, learning English is not easy."},
        {"part": 1, "speaker": "Lin Na",   "chinese": "您今年多大岁数？",                             "pinyin": "Nín jīnnián duōdà suìshu?",                           "english": "How old are you this year?"},
        {"part": 1, "speaker": "Driver",   "chinese": "我今年五十二。语言学院到了。现在差五分八点，您还有五分钟。", "pinyin": "Wǒ jīnnián wǔshí'èr. Yǔyán xuéyuàn dàole. Xiànzài chà wǔ fēn bā diǎn, nín hái yǒu wǔ fēnzhōng.", "english": "I am 52 this year. We've arrived at the Institute of Languages. It's now five-to-eight, you still have five minutes."},
        {"part": 1, "speaker": "Lin Na",   "chinese": "谢谢，给您钱。",                               "pinyin": "Xièxie, gěi nín qián.",                                "english": "Thanks, here is your money."},
        {"part": 1, "speaker": "Driver",   "chinese": "您给我二十，找您五块四，OK？",                 "pinyin": "Nín gěi wǒ èrshí, zhǎo nín wǔ kuài sì, OK?",         "english": "You gave me 20, here's 5.40 yuan change, OK?"},
        {"part": 1, "speaker": "Lin Na",   "chinese": "您会说英语！",                                 "pinyin": "Nín huì shuō yīngyǔ!",                                "english": "You can speak English!"},
        {"part": 1, "speaker": "Driver",   "chinese": "我也会一点儿。拜拜！",                         "pinyin": "Wǒ yě huì yìdiǎnr. Bàibài!",                         "english": "I also can speak a little. Bye-bye!"},
        {"part": 1, "speaker": "Lin Na",   "chinese": "拜拜！",                                       "pinyin": "Bàibài!",                                             "english": "Bye-bye!"},
        {"part": 2, "speaker": "Wang Xiaoyun", "chinese": "陈老师，马大为今天不能来上课。",           "pinyin": "Chén lǎoshī, Mǎ Dàwéi jīntiān bùnéng lái shàngkè.", "english": "Teacher Chen, Ma Dawei cannot come to class today."},
        {"part": 2, "speaker": "Teacher Chen", "chinese": "他为什么不能来上课？",                     "pinyin": "Tā wèishéme bùnéng lái shàngkè?",                    "english": "Why can't he come to class?"},
        {"part": 2, "speaker": "Wang Xiaoyun", "chinese": "昨天是星期日，他上午去商场买东西，下午去朋友家玩儿。他晚上十一点半回学院，十二点写汉字，两点钟睡觉。现在还没有起床。", "pinyin": "Zuótiān shì xīngqīrì, tā shàngwǔ qù shāngchǎng mǎi dōngxi, xiàwǔ qù péngyǒu jiā wánr. Tā wǎnshang shíyī diǎn bàn huí xuéyuàn, shí'èr diǎn xiě hànzì, liǎng diǎn zhōng shuìjiào. Xiànzài hái méiyǒu qǐchuáng.", "english": "Yesterday was Sunday. In the morning he went to the mall shopping, in the afternoon he went to a friend's house. He got back to campus at half-past eleven, wrote characters at twelve and slept at two. Now he still hasn't got up."},
        {"part": 2, "speaker": "Teacher Chen", "chinese": "他应该来上课。",                           "pinyin": "Tā yīnggāi lái shàngkè.",                             "english": "He should come to class."},
        {"part": 2, "speaker": "Wang Xiaoyun", "chinese": "老师，我能不能问您一个问题？",             "pinyin": "Lǎoshī, wǒ néng bu néng wèn nín yígè wèntí?",        "english": "Teacher, can I ask you a question?"},
        {"part": 2, "speaker": "Teacher Chen", "chinese": "可以。",                                   "pinyin": "Kěyǐ.",                                               "english": "Yes."},
        {"part": 2, "speaker": "Wang Xiaoyun", "chinese": "我们为什么八点上课？",                     "pinyin": "Wǒmen wèishéme bā diǎn shàngkè?",                    "english": "Why do we start class at eight o'clock?"},
    ],
    12: [
        {"part": 1, "speaker": "Libo",      "chinese": "大为，你每天都六点起床去锻炼，现在九点一刻，你怎么还不起床？", "pinyin": "Dàwéi, nǐ měitiān dōu liù diǎn qǐchuáng qù duànliàn, xiànzài jiǔ diǎn yíkè, nǐ zěnme hái bù qǐchuáng?", "english": "Dawei, you get up at six every day to exercise. It's quarter-past-nine — how come you are still not up?"},
        {"part": 1, "speaker": "Ma Dawei", "chinese": "我头疼。",                                     "pinyin": "Wǒ tóuténg.",                                          "english": "I have a headache."},
        {"part": 1, "speaker": "Libo",     "chinese": "你嗓子怎么样？",                               "pinyin": "Nǐ sǎngzi zěnme yàng?",                               "english": "How's your throat?"},
        {"part": 1, "speaker": "Ma Dawei", "chinese": "我嗓子也疼。",                                 "pinyin": "Wǒ sǎngzi yě téng.",                                  "english": "My throat is also paining."},
        {"part": 1, "speaker": "Libo",     "chinese": "我想，你应该去医院看病。",                     "pinyin": "Wǒ xiǎng, nǐ yīnggāi qù yīyuàn kànbìng.",            "english": "I think you should go to the hospital and see a doctor."},
        {"part": 1, "speaker": "Ma Dawei", "chinese": "我身体没问题，不用去看病。我要睡觉，不想去医院。", "pinyin": "Wǒ shēntǐ méi wèntí, búyòng qù kànbìng. Wǒ yào shuìjiào, bùxiǎng qù yīyuàn.", "english": "My health is fine, no need to see a doctor. I want to sleep, don't want to go to hospital."},
        {"part": 1, "speaker": "Libo",     "chinese": "你不去看病，明天你还不能上课。",               "pinyin": "Nǐ bù qù kànbìng, míngtiān nǐ hái bù néng shàngkè.", "english": "If you don't see a doctor, tomorrow you still won't be able to attend class."},
        {"part": 1, "speaker": "Ma Dawei", "chinese": "好吧，我去医院。现在去还是下午去？",           "pinyin": "Hǎo ba, wǒ qù yīyuàn. Xiànzài qù háishì xiàwǔ qù?", "english": "OK then, I'll go to the hospital. Do we go now or in the afternoon?"},
        {"part": 1, "speaker": "Libo",     "chinese": "当然现在去，我跟你一起去。今天天气很冷，你要多穿点儿衣服。", "pinyin": "Dāngrán xiànzài qù, wǒ gēn nǐ yīqǐ qù. Jīntiān tiānqì hěn lěng, nǐ yào duō chuān diǎnr yīfu.", "english": "Of course go now, I'll come with you. The weather is cold today, you should wear more clothing."},
        {"part": 2, "speaker": "Libo",     "chinese": "你在这儿休息一下，我去给你挂号。",             "pinyin": "Nǐ zài zhèr xiūxí yíxià, wǒ qù gěi nǐ guàhào.",     "english": "You rest here, I'll go register for you."},
        {"part": 2, "speaker": "Ma Dawei", "chinese": "好。",                                         "pinyin": "Hǎo.",                                                "english": "Thanks."},
        {"part": 2, "speaker": "Nurse",    "chinese": "八号，八号是谁？",                             "pinyin": "Bā hào, bā hào shì sheí?",                            "english": "Number eight, who is number eight?"},
        {"part": 2, "speaker": "Ma Dawei", "chinese": "我是八号。",                                   "pinyin": "Wǒ shì bā hào.",                                      "english": "I am number eight."},
        {"part": 2, "speaker": "Nurse",    "chinese": "你看病还是他看病？",                           "pinyin": "Nǐ kànbìng háishì tā kànbìng?",                       "english": "Are you here to see the doctor or is it he?"},
        {"part": 2, "speaker": "Libo",     "chinese": "他看病。",                                     "pinyin": "Tā kànbìng.",                                         "english": "He is here to see the doctor."},
        {"part": 2, "speaker": "Doctor",   "chinese": "请坐吧。你叫马大为，是不是？",                 "pinyin": "Qǐng zuò ba. Nǐ jiào Mǎ Dàwéi, shì bu shì?",        "english": "Please take a seat. You are Ma Dawei, right?"},
        {"part": 2, "speaker": "Ma Dawei", "chinese": "是，我叫马大为。",                             "pinyin": "Shì, wǒ jiào Mǎ Dàwéi.",                              "english": "Yes, I am Ma Dawei."},
        {"part": 2, "speaker": "Doctor",   "chinese": "你今年多大？",                                 "pinyin": "Nǐ jīnnián duōdà?",                                   "english": "How old are you this year?"},
        {"part": 2, "speaker": "Ma Dawei", "chinese": "我今年二十二岁。",                             "pinyin": "Wǒ jīnnián èrshí'èr suì.",                            "english": "I am twenty-two years old."},
        {"part": 2, "speaker": "Doctor",   "chinese": "你哪儿不舒服？",                               "pinyin": "Nǐ nǎr bù shūfu?",                                   "english": "Where are you feeling uncomfortable?"},
        {"part": 2, "speaker": "Ma Dawei", "chinese": "我头疼，全身都不舒服。",                       "pinyin": "Wǒ tóuténg, quánshēn dōu bù shūfu.",                  "english": "I have a headache, and I feel unwell all over my body."},
        {"part": 2, "speaker": "Doctor",   "chinese": "我看一下。你嗓子有点儿发炎，还有点儿发烧，是感冒。", "pinyin": "Wǒ kàn yíxià. Nǐ sǎngzi yǒudiǎnr fāyán, hái yǒudiǎnr fāshāo, shì gǎnmào.", "english": "Let me take a look. Your throat is a little inflamed, you have a bit of a fever — it's a cold."},
        {"part": 2, "speaker": "Libo",     "chinese": "他要不要住院？",                               "pinyin": "Tā yào búyào zhùyuàn?",                               "english": "Does he need to be hospitalised?"},
        {"part": 2, "speaker": "Doctor",   "chinese": "不用。你要多喝水，还要吃点儿药。你愿意吃中药还是愿意吃西药？", "pinyin": "Búyòng. Nǐ yào duō hē shuǐ, hái yào chī diǎnr yào. Nǐ yuànyì chī zhōngyào háishì yuànyì chī xīyào?", "english": "No need. You should drink lots of water and take some medicine. Are you willing to take Chinese medicine or Western medicine?"},
        {"part": 2, "speaker": "Ma Dawei", "chinese": "我愿意吃中药。",                               "pinyin": "Wǒ yuànyì chī zhōngyào.",                              "english": "I'm willing to take Chinese medicine."},
        {"part": 2, "speaker": "Doctor",   "chinese": "好，你吃一点儿中药，下星期一再来。",           "pinyin": "Hǎo, nǐ chī yìdiǎnr zhōngyào, xià xīngqī yī zàilái.", "english": "OK, take some Chinese medicine, and come back next Monday."},
        {"part": 2, "speaker": "Ma Dawei", "chinese": "好，谢谢。",                                   "pinyin": "Hǎo, xièxie.",                                        "english": "OK, thanks."},
    ],
    13: [
        {"part": 1, "speaker": "Song Hua",  "chinese": "大为，听说你得了感冒，现在你身体怎么样？",   "pinyin": "Dàwéi, tīng shuō nǐ dé le gǎnmào, xiànzài nǐ shēntǐ zěnme yàng?", "english": "Dawei, I heard you caught a cold — how's your health now?"},
        {"part": 1, "speaker": "Ma Dawei", "chinese": "我去了医院，吃了很多中药。现在我头还有点儿疼。", "pinyin": "Wǒ qùle yīyuàn, chīle hěnduō zhōngyào. Xiànzài wǒ tóu hái yǒudiǎnr téng.", "english": "I went to the hospital and took a lot of Chinese medicine. I still have a little bit of a headache."},
        {"part": 1, "speaker": "Song Hua",  "chinese": "你还应该多休息。",                           "pinyin": "Nǐ hái yīnggāi duō xiūxi.",                           "english": "You still have to take more rest."},
        {"part": 1, "speaker": "Ma Dawei", "chinese": "宋华，我想告诉你一件事儿。",                   "pinyin": "Sòng Huá, wǒ xiǎng gàosu nǐ yí jiàn shìr.",          "english": "Song Hua, I want to tell you something."},
        {"part": 1, "speaker": "Song Hua",  "chinese": "什么事儿？",                                 "pinyin": "Shénme shìr?",                                        "english": "What's it?"},
        {"part": 1, "speaker": "Ma Dawei", "chinese": "我认识了一个漂亮的姑娘，她愿意做我女朋友。我们常常一起散步，一起看电影、喝咖啡，一起听音乐。", "pinyin": "Wǒ rènshile yíge piàoliang de gūniang, tā yuànyì zuò wǒ nǚ péngyou. Wǒmen chángcháng yìqǐ sànbù, yìqǐ kàn diànyǐng, hē kāfēi, yìqǐ tīng yīnyuè.", "english": "I've met a pretty girl and she's willing to be my girlfriend. We often go walking together, watch movies, drink coffee, and listen to music together."},
        {"part": 1, "speaker": "Song Hua",  "chinese": "祝贺你！这是好事啊。",                       "pinyin": "Zhùhè nǐ! Zhè shì hǎoshì a.",                         "english": "Congratulations! This is a good thing."},
        {"part": 1, "speaker": "Ma Dawei", "chinese": "谢谢。是好事，可是我的宿舍太小，她不能常来我这儿。我想找一间房子。", "pinyin": "Xièxie. Shì hǎoshì, kěshì wǒ de sùshè tài xiǎo, tā bùnéng cháng lái wǒ zhèr. Wǒ xiǎng zhǎo yí jiàn fángzi.", "english": "Thanks. It is a good thing, but my dormitory is too small, she cannot often come to my place. I want to find a room."},
        {"part": 1, "speaker": "Song Hua",  "chinese": "你想租房子？",                               "pinyin": "Nǐ xiǎng zūfángzi?",                                  "english": "You want to rent a house?"},
        {"part": 1, "speaker": "Ma Dawei", "chinese": "是啊，我想租一间有厨房和厕所的房子，房租不能太贵。", "pinyin": "Shì a, wǒ xiǎng zū yí jiàn yǒu chúfáng hé cèsuǒ de fángzi, fángzū bùnéng tài guì.", "english": "Yes, I want to rent a house with a kitchen and toilet, the rent should not be too expensive."},
        {"part": 1, "speaker": "Song Hua",  "chinese": "星期六，我跟你一起去租房公司，好吗？",       "pinyin": "Xīngqīliù, wǒ gēn nǐ yìqǐ qù zū fáng gōngsī, hǎo ma?", "english": "Saturday, I will come along with you to a house rental agency, OK?"},
        {"part": 1, "speaker": "Ma Dawei", "chinese": "太好了。",                                     "pinyin": "Tài hǎole.",                                          "english": "That would be great."},
        {"part": 1, "speaker": "Song Hua",  "chinese": "好，再见。",                                 "pinyin": "Hǎo, zàijiàn.",                                       "english": "OK, see you later."},
        {"part": 1, "speaker": "Ma Dawei", "chinese": "再见。",                                       "pinyin": "Zàijiàn.",                                            "english": "See you."},
        {"part": 2, "speaker": "Ma Dawei", "chinese": "那间房子房租太贵，你说，我应该怎么办？",       "pinyin": "Nà jiān fángzi fángzū tài guì, nǐ shuō, wǒ yīnggāi zěnme bàn?", "english": "The rent for that house is too expensive — what should I do?"},
        {"part": 2, "speaker": "Song Hua",  "chinese": "你想租还是不想租？",                         "pinyin": "Nǐ xiǎng zū háishì bù xiǎng zū?",                    "english": "Do you want to rent it or not?"},
        {"part": 2, "speaker": "Ma Dawei", "chinese": "当然想租。",                                   "pinyin": "Dāngrán xiǎng zū.",                                   "english": "Of course I want to rent it."},
        {"part": 2, "speaker": "Song Hua",  "chinese": "我给陆雨平打个电话，让他来帮助我们。",       "pinyin": "Wǒ gěi Lù Yǔpíng dǎ ge diànhuà, ràng tā lái bāngzhù wǒmen.", "english": "I'll give Lu Yuping a call and ask him to help us."},
        {"part": 2, "speaker": "Ma Dawei", "chinese": "他很忙，会来吗？",                             "pinyin": "Tā hěn máng, huì lái ma?",                            "english": "He is very busy, will he come?"},
        {"part": 2, "speaker": "Song Hua",  "chinese": "他会来。",                                   "pinyin": "Tā huì lái.",                                         "english": "He will come."},
        {"part": 2, "speaker": "Lu Yuping", "chinese": "喂，哪一位啊？",                             "pinyin": "Wéi, nǎ yí wèi a?",                                   "english": "Hello, who is this?"},
        {"part": 2, "speaker": "Song Hua",  "chinese": "我是宋华，我和大为现在在家美租房公司。",     "pinyin": "Wǒ shì Sòng Huá, wǒ hé Dàwéi xiànzài zài Jiāměi zūfáng gōngsī.", "english": "It's me Song Hua, I'm with Dawei at the Jiamei house rental agency."},
        {"part": 2, "speaker": "Lu Yuping", "chinese": "你们怎么在那儿？",                           "pinyin": "Nǐmen zěnme zài nàr?",                                "english": "What are you two doing there?"},
        {"part": 2, "speaker": "Song Hua",  "chinese": "大为要租房子。",                             "pinyin": "Dàwéi yào zū fángzi.",                                "english": "Dawei wants to rent a house."},
        {"part": 2, "speaker": "Lu Yuping", "chinese": "你们看没看房子？",                           "pinyin": "Nǐmen kàn méi kàn fángzi?",                           "english": "Have you seen the house or not?"},
        {"part": 2, "speaker": "Song Hua",  "chinese": "我们看一间房子。那间房子很好，可是房租有点儿贵。", "pinyin": "Wǒmen kàn yí jiàn fángzi. Nà jiān fángzi hěn hǎo, kěshì fángzū yǒudiǎnr guì.", "english": "We have seen one apartment. That apartment is very good, but the rent is a little expensive."},
        {"part": 2, "speaker": "Lu Yuping", "chinese": "你们找了经理没有？",                         "pinyin": "Nǐmen zhǎo le jīnglǐ méiyǒu?",                        "english": "Have you talked to the manager?"},
        {"part": 2, "speaker": "Song Hua",  "chinese": "我们没有找经理。",                           "pinyin": "Wǒmen méiyǒu zhǎo jīnglǐ.",                           "english": "We haven't talked to the manager."},
        {"part": 2, "speaker": "Lu Yuping", "chinese": "宋华，这个公司的经理是我朋友，我跟他说一下，请他帮助你们，我想可能没有问题。", "pinyin": "Sòng Huá, zhège gōngsī de jīnglǐ shì wǒ péngyǒu, wǒ gēn tā shuō yíxià, qǐng tā bāngzhù nǐmen, wǒ xiǎng kěnéng méiyǒu wèntí.", "english": "Song Hua, that company's manager is my friend. I'll speak to him and ask him to help you — I think there should be no problem."},
        {"part": 2, "speaker": "Song Hua",  "chinese": "好啊。晚上我们请你和你朋友吃饭。",         "pinyin": "Hǎo a. Wǎnshang wǒmen qǐng nǐ hé nǐ péngyǒu chīfàn.", "english": "Great. This evening we will invite you and your friend to dinner."},
        {"part": 2, "speaker": "Lu Yuping", "chinese": "好，你们在公司等我，再见。",                 "pinyin": "Hǎo, nǐmen zài gōngsī děng wǒ, zàijiàn.",            "english": "OK, you wait for me at the company, see you."},
        {"part": 2, "speaker": "Song Hua",  "chinese": "再见。",                                     "pinyin": "Zàijiàn.",                                            "english": "See you."},
        {"part": 2, "speaker": "Ma Dawei", "chinese": "没问题，走吧。",                               "pinyin": "Méi wèntí, zǒu ba.",                                  "english": "No problem, let's go."},
    ],
    14: [
        {"part": 1, "speaker": "Ma Dawei", "chinese": "力波，上午十点半，你妈妈给你打了一个电话。我告诉她你不在。我让她中午再给你打。", "pinyin": "Lìbō, shàngwǔ shí diǎn bàn, nǐ māma gěi nǐ dǎle yí ge diànhuà. Wǒ gàosu tā nǐ búzài. Wǒ ràng tā zhōngwǔ zài gěi nǐ dǎ.", "english": "Libo, your mother called at 10:30 this morning. I told her you were not there and asked her to call again at noon."},
        {"part": 1, "speaker": "Libo",     "chinese": "谢谢。我刚才去邮局给我妈妈寄了点儿东西。大为，我今天打扫了宿舍，你的脏衣服太多了。", "pinyin": "Xièxie. Wǒ gāngcái qù yóujú gěi wǒ māma jìle diǎnr dōngxi. Dàwéi, wǒ jīntiān dǎsǎole sùshè, nǐ de zāng yīfu tài duō le.", "english": "Thanks. I just went to the post office to send my mom some things. Dawei, I cleaned the dormitory today — your dirty clothes are too many."},
        {"part": 1, "speaker": "Ma Dawei", "chinese": "不好意思。这两天我太忙了，我想星期六一起洗。", "pinyin": "Bù hǎoyìsi. Zhè liǎng tiān wǒ tài máng le, wǒ xiǎng xīngqīliù yìqǐ xǐ.", "english": "Sorry. I've been very busy these past couple of days. I want to wash them all together on Saturday."},
        {"part": 1, "speaker": "Ma Dawei", "chinese": "喂，你好，你找谁？啊，丁力波在，请等一下。力波，你妈妈的电话。", "pinyin": "Wéi, nǐ hǎo, nǐ zhǎo sheí? A, Dīng Lìbō zài, qǐng děng yíxià. Lìbō, nǐ māma de diànhuà.", "english": "Hello, who are you looking for? Ah, Ding Libo is here, please wait a moment. Libo, your mother's call."},
        {"part": 1, "speaker": "Libo",     "chinese": "谢谢。妈妈，你好！",                           "pinyin": "Xièxie. Māma, nǐ hǎo!",                               "english": "Thanks. Hello mom!"},
        {"part": 2, "speaker": "Mother",   "chinese": "力波，你好吗？",                               "pinyin": "Lìbō, nǐ hǎo ma?",                                    "english": "Libo, how are you?"},
        {"part": 2, "speaker": "Libo",     "chinese": "我很好。你和爸爸身体怎么样？",                 "pinyin": "Wǒ hěn hǎo. Nǐ hé bàba shēntǐ zěnme yàng?",          "english": "I'm fine. How is the health of you and dad?"},
        {"part": 2, "speaker": "Mother",   "chinese": "我身体很好，你爸爸也很好。我们工作都很忙。你外婆身体好吗？", "pinyin": "Wǒ shēntǐ hěn hǎo, nǐ bàba yě hěn hǎo. Wǒmen gōngzuò dōu hěn máng. Nǐ wàipó shēntǐ hǎo ma?", "english": "I'm well, and your dad is also fine. We are both very busy with work. How is your grandmother's health?"},
        {"part": 2, "speaker": "Libo",     "chinese": "她身体很好。她让我问你们好。",                 "pinyin": "Tā shēntǐ hěn hǎo. Tā ràng wǒ wèn nǐmen hǎo.",       "english": "She's well. She asked me to convey her regards to you."},
        {"part": 2, "speaker": "Mother",   "chinese": "我们也问她好。你哥哥，弟弟怎么样？",           "pinyin": "Wǒmen yě wèn tā hǎo. Nǐ gēge, dìdi zěnme yàng?",    "english": "We also send our regards to her. How are your elder and younger brothers?"},
        {"part": 2, "speaker": "Libo",     "chinese": "他们也都很好。哥哥现在在一个中学打工，弟弟在南方旅行。我们都很想你们。", "pinyin": "Tāmen yě dōu hěn hǎo. Gēge xiànzài zài yígè zhōngxué dǎgōng, dìdi zài nánfāng lǚxíng. Wǒmen dōu hěn xiǎng nǐmen.", "english": "They are both doing well. Older brother is currently working at a middle school, younger brother is travelling in the south. We all miss you both."},
        {"part": 2, "speaker": "Mother",   "chinese": "我们也想你们。你现在怎么样？你住的宿舍大不大？住几个人？", "pinyin": "Wǒmen yě xiǎng nǐmen. Nǐ xiànzài zěnme yàng? Nǐ zhù de sùshè dà bu dà? Zhù jǐ ge rén?", "english": "We also miss you all. How are you now? Is your dormitory big? How many people live there?"},
        {"part": 2, "speaker": "Libo",     "chinese": "我们留学生楼两个人住一间。我跟一个美国人住，他的中文名字叫马大为。", "pinyin": "Wǒmen liúxuéshēng lóu liǎng ge rén zhù yí jiān. Wǒ gēn yígè Měiguó rén zhù, tā de zhōngwén míngzi jiào Mǎ Dàwéi.", "english": "In our foreign students' building, two people share a room. I am living with an American, his Chinese name is Ma Dawei."},
        {"part": 2, "speaker": "Mother",   "chinese": "他也学习汉语吗？",                             "pinyin": "Tā yě xuéxí hànyǔ ma?",                               "english": "Is he also learning Chinese?"},
        {"part": 2, "speaker": "Libo",     "chinese": "对，他也学习汉语。我还有很多中国朋友，他们常常帮助我念生词，复习课文，练习口语。我还常常问他们语法问题，他们都是我的好朋友。", "pinyin": "Duì, tā yě xuéxí hànyǔ. Wǒ hái yǒu hěnduō Zhōngguó péngyou, tāmen chángcháng bāngzhù wǒ niàn shēngcí, fùxí kèwén, liànxí kǒuyǔ. Wǒ hái chángcháng wèn tāmen yǔfǎ wèntí, tāmen dōu shì wǒ de hǎo péngyou.", "english": "Yes, he is also learning Chinese. I also have many Chinese friends who often help me read new words, revise texts, and practise speaking. I also often ask them grammar questions — they are all my good friends."},
        {"part": 2, "speaker": "Mother",   "chinese": "这很好。力波，今年你要在中国过圣诞节，不能回家，我和你爸爸要送你一件圣诞礼物。", "pinyin": "Zhè hěn hǎo. Lìbō, jīnnián nǐ yào zài Zhōngguó guò shèngdànjié, bù néng huíjiā, wǒ hé nǐ bàba yào sòng nǐ yí jiàn shèngdàn lǐwù.", "english": "That's great. Libo, this year you will be spending Christmas in China and cannot come home, so me and your father want to send you a Christmas present."},
        {"part": 2, "speaker": "Libo",     "chinese": "谢谢你们。我也给你们寄了圣诞礼物。",           "pinyin": "Xièxie nǐmen. Wǒ yě gěi nǐmen jìle shèngdàn lǐwù.", "english": "Thank you both. I have also sent you a Christmas present."},
        {"part": 2, "speaker": "Mother",   "chinese": "是吗？圣诞节我和你爸爸想去欧洲旅行。你呢？你去不去旅行？", "pinyin": "Shì ma? Shèngdànjié wǒ hé nǐ bàba xiǎng qù Ōuzhōu lǚxíng. Nǐ ne? Nǐ qù bu qù lǚxíng?", "english": "Really? During the Christmas holiday me and your dad are thinking of going travelling in Europe. How about you? Will you go travelling?"},
        {"part": 2, "speaker": "Libo",     "chinese": "我要去上海旅行。",                             "pinyin": "Wǒ yào qù Shànghǎi lǚxíng.",                          "english": "I want to go on a trip to Shanghai."},
        {"part": 2, "speaker": "Mother",   "chinese": "上海很漂亮。祝你旅行快乐！",                   "pinyin": "Shànghǎi hěn piàoliang. Zhù nǐ lǚxíng kuàilè!",     "english": "Shanghai is beautiful. Wishing you a happy trip!"},
        {"part": 2, "speaker": "Libo",     "chinese": "谢谢。我也祝你和爸爸圣诞快乐！",               "pinyin": "Xièxie. Wǒ yě zhù nǐ hé bàba shèngdàn kuàilè!",    "english": "Thanks. I also wish you and dad a Merry Christmas!"},
        {"part": 2, "speaker": "Mother",   "chinese": "好，就这儿吧。",                               "pinyin": "Hǎo, jiù zhèr ba.",                                   "english": "OK, well that's it."},
    ],
}

import pprint

def dialogue_to_python(dialogue):
    lines = []
    for entry in dialogue:
        lines.append(
            f'            {{"part": {entry["part"]}, "speaker": {repr(entry["speaker"])}, '
            f'"chinese": {repr(entry["chinese"])}, '
            f'"pinyin": {repr(entry["pinyin"])}, '
            f'"english": {repr(entry["english"])}}}'
        )
    return "[\n" + ",\n".join(lines) + ",\n        ]"

with open("seed_data.py", "r", encoding="utf-8") as f:
    content = f.read()

for lesson_num, dialogue in NEW_DIALOGUES.items():
    # Find this lesson's dialogue block using a unique anchor
    anchor = f'"lesson_number": {lesson_num},'
    lesson_start = content.find(anchor)
    if lesson_start == -1:
        print(f"WARNING: could not find lesson {lesson_num}")
        continue
    # Find "dialogue": [ after the anchor
    dial_start = content.find('"dialogue": [', lesson_start)
    if dial_start == -1:
        print(f"WARNING: could not find dialogue for lesson {lesson_num}")
        continue
    # Find the matching closing ], by tracking bracket depth
    pos = dial_start + len('"dialogue": [')
    depth = 1
    while pos < len(content) and depth > 0:
        if content[pos] == '[':
            depth += 1
        elif content[pos] == ']':
            depth -= 1
        pos += 1
    old_block = content[dial_start:pos]
    new_block = '"dialogue": ' + dialogue_to_python(dialogue)
    content = content[:dial_start] + new_block + content[pos:]
    print(f"Replaced dialogue for lesson {lesson_num} ({len(dialogue)} entries)")

with open("seed_data.py", "w", encoding="utf-8") as f:
    f.write(content)

print("Done. seed_data.py updated.")
