import { StyleSheet } from 'react-native';
import { colors, spacing, radius, fontSize, shadows, accents } from '@/src/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  flex: { flex: 1 },
  loading: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.background },
  header: { paddingHorizontal: spacing.lg, paddingTop: spacing.md, paddingBottom: spacing.sm, flexDirection: 'row', alignItems: 'center', gap: spacing.md },
  progressBar: { flex: 1, height: 4, backgroundColor: colors.border, borderRadius: radius.full, overflow: 'hidden' },
  progressFill: { height: '100%', backgroundColor: colors.primary, borderRadius: radius.full },
  progressText: { fontSize: fontSize.sm, color: colors.textSecondary, fontWeight: '500' },
  modeBanner: {
    marginHorizontal: spacing.lg,
    marginTop: spacing.sm,
    padding: spacing.md,
    backgroundColor: colors.primaryLight,
    borderRadius: radius.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  modeLabel: { fontSize: fontSize.base, color: colors.textPrimary, fontWeight: '600' },
  modeDesc: { fontSize: fontSize.xs, color: colors.textSecondary, marginTop: 2 },
  stageLabel: { fontSize: 10, color: colors.textTertiary, textTransform: 'uppercase', letterSpacing: 1, fontWeight: '500' },
  cardScroll: { flexGrow: 1, padding: spacing.lg },
  card: { backgroundColor: colors.surface, borderRadius: radius.xl, padding: spacing.lg, gap: spacing.sm, borderWidth: 1, borderColor: colors.border, ...shadows.md },
  hanzi: { fontSize: fontSize.hanziLg, color: colors.textPrimary, fontWeight: '500', textAlign: 'center' },
  englishPrompt: { fontSize: fontSize.xxl, color: colors.textPrimary, fontWeight: '400', textAlign: 'center', marginTop: spacing.sm },
  pinyinSmall: { fontSize: fontSize.sm, color: colors.textTertiary, textAlign: 'center' },
  writePrompt: { fontSize: fontSize.xs, color: colors.textTertiary, textAlign: 'center', textTransform: 'uppercase', letterSpacing: 1, marginTop: spacing.md, marginBottom: spacing.sm },
  inputLabel: { fontSize: fontSize.sm, color: colors.textSecondary, fontWeight: '500', marginTop: spacing.lg },
  input: { borderBottomWidth: 2, borderBottomColor: colors.textPrimary, paddingVertical: spacing.md, fontSize: fontSize.xl, color: colors.textPrimary, textAlign: 'center', minHeight: 56 },
  inputCorrect: { borderBottomColor: colors.success },
  inputIncorrect: { borderBottomColor: colors.error },
  canvasWrap: { marginTop: spacing.md },
  feedback: { padding: spacing.md, borderRadius: radius.lg, marginTop: spacing.md, gap: spacing.xs, flexDirection: 'column' },
  feedbackHeader: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  feedbackCorrect: { backgroundColor: colors.successLight },
  feedbackIncorrect: { backgroundColor: colors.errorLight },
  feedbackTitle: { fontSize: fontSize.base, fontWeight: '600' },
  englishAnswer: { fontSize: fontSize.base, color: colors.textPrimary, marginTop: 4 },
  compareLabel: { fontSize: 10, color: colors.textTertiary, textTransform: 'uppercase', letterSpacing: 1, marginTop: spacing.sm },
  compareHanzi: { fontSize: fontSize.xl, color: colors.textPrimary, marginTop: 2 },
  scoreText: { fontSize: fontSize.sm, color: colors.textSecondary, marginTop: spacing.sm },
  toneNote: { fontSize: fontSize.sm, color: colors.textSecondary, fontStyle: 'italic', marginTop: spacing.sm, textAlign: 'center' },
  // Writing feedback
  writingFeedback: { marginTop: spacing.md, gap: spacing.sm },
  charTileRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, justifyContent: 'center' },
  charTile: {
    width: 88,
    borderRadius: radius.lg,
    borderWidth: 1.5,
    padding: spacing.sm,
    alignItems: 'center',
    gap: 4,
  },
  charTileGood: { backgroundColor: colors.successLight, borderColor: colors.success },
  charTileBad: { backgroundColor: colors.errorLight, borderColor: colors.error },
  charTileBlank: { backgroundColor: colors.surfaceAlt, borderColor: colors.borderStrong },
  charTargetLabel: { fontSize: 10, color: colors.textTertiary, textTransform: 'uppercase', letterSpacing: 0.5 },
  charRecognized: { fontSize: fontSize.xxl, color: colors.textPrimary, fontWeight: '500' },
  qualityBar: { width: '100%', height: 4, backgroundColor: colors.border, borderRadius: radius.full, overflow: 'hidden', marginTop: 2 },
  qualityFill: { height: '100%', borderRadius: radius.full },
  qualityPct: { fontSize: 10, color: colors.textSecondary, fontWeight: '600' },
  charNote: { fontSize: 10, color: colors.textSecondary, textAlign: 'center', lineHeight: 14 },
  subScore: { fontSize: fontSize.sm, color: colors.textSecondary, textAlign: 'center', fontWeight: '500', marginTop: spacing.xs },
  overallNotes: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.xs, backgroundColor: colors.surfaceAlt, borderRadius: radius.md, padding: spacing.sm },
  overallNotesText: { flex: 1, fontSize: fontSize.sm, fontWeight: '500', lineHeight: 20 },
  correctBtnMuted: { backgroundColor: colors.surfaceAlt, borderWidth: 1, borderColor: colors.success },
  settingsBtn: { backgroundColor: colors.primary, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderRadius: radius.sm, alignSelf: 'flex-start', marginTop: spacing.sm, minHeight: 36, justifyContent: 'center' },
  settingsBtnText: { color: '#fff', fontWeight: '600', fontSize: fontSize.sm },
  footer: { padding: spacing.lg },
  primaryBtn: { backgroundColor: colors.primary, borderRadius: radius.md, paddingVertical: 16, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: spacing.sm, minHeight: 52 },
  primaryBtnText: { color: '#fff', fontSize: fontSize.lg, fontWeight: '600' },
  btnDisabled: { opacity: 0.5 },
  recordingDot: { width: 12, height: 12, borderRadius: 6, backgroundColor: '#fff' },
  actionRow: { flexDirection: 'row', gap: spacing.md },
  actionBtn: { flex: 1, borderRadius: radius.lg, padding: spacing.md, alignItems: 'center', gap: spacing.xs, minHeight: 64, justifyContent: 'center', flexDirection: 'row' },
  correctBtn: { backgroundColor: colors.successLight, borderWidth: 1, borderColor: colors.success },
  incorrectBtn: { backgroundColor: colors.errorLight, borderWidth: 1, borderColor: colors.error },
  actionLabel: { fontSize: fontSize.sm, fontWeight: '600' },
  emptyContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: spacing.xl },
  emptyBadge: {
    width: 160,
    height: 160,
    borderRadius: radius.full,
    backgroundColor: accents.green.soft,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.lg,
  },
  emptyHanzi: { fontSize: 58, color: colors.primary, fontWeight: '700', textAlign: 'center' },
  emptyTitle: { fontSize: fontSize.xxl, color: colors.textPrimary, fontWeight: '700' },
  emptySub: { fontSize: fontSize.base, color: colors.textSecondary, textAlign: 'center', marginTop: spacing.md, paddingHorizontal: spacing.xl, lineHeight: 22 },
  emptyBtn: { backgroundColor: colors.primary, paddingHorizontal: spacing.xl, paddingVertical: 14, borderRadius: radius.full, marginTop: spacing.xl, minHeight: 48, justifyContent: 'center', ...shadows.glow(accents.green.base) },
  emptyBtnSecondary: { backgroundColor: 'transparent', borderWidth: 1.5, borderColor: colors.primary, marginTop: spacing.md, shadowOpacity: 0, elevation: 0 },
  emptyBtnText: { color: '#fff', fontSize: fontSize.base, fontWeight: '600' },
  emptyBtnTextSecondary: { color: colors.primary },
  // Done / summary screen
  doneScroll: { alignItems: 'center', paddingVertical: spacing.xxl, paddingHorizontal: spacing.lg },
  doneBtn: { alignSelf: 'stretch', marginTop: spacing.md },
  summarySection: { alignSelf: 'stretch', marginTop: spacing.xl },
  summaryHeader: { fontSize: fontSize.sm, color: colors.textTertiary, textTransform: 'uppercase', letterSpacing: 1, fontWeight: '600', marginBottom: spacing.sm },
  summaryRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, backgroundColor: colors.surface, borderRadius: radius.lg, padding: spacing.md, marginBottom: spacing.sm, borderWidth: 1, borderColor: colors.border, ...shadows.sm },
  summaryHanzi: { fontSize: fontSize.xl, color: colors.textPrimary, fontWeight: '500', minWidth: 44, textAlign: 'center' },
  summaryRight: { flex: 1, gap: 2 },
  summaryEnglish: { fontSize: fontSize.base, color: colors.textPrimary },
  summaryStage: { fontSize: fontSize.xs, color: colors.textTertiary },
});
